### ISSUE TITLE
this.eventSource.removeEventListener() requires parameters

### ISSUE THREAD

**Issue by utillity** [NervosaX/Backbone.EventSource#1]
Firefox console shows an error.

this.eventSource.removeEventListener()
replaced by 
this.eventSource.removeEventListener(null, null)

solves the problem.

**Comment by NervosaX** [comment]
Cripes. Forgot I even made this thing. I'm trying to run my example but it does not seem to want to work anymore.

I don't use this project, but I'm happy to blindly fix it with your fix above. :)

**Comment by utillity** [comment]
thanks. There's another bug in connect-sse (https://github.com/andrewrk/connect-sse/issues/6) which stops your example from working. But fixing both your code works just fine now :)

**Comment by NervosaX** [comment]
Yep, that's the error I was getting too.
